### PR TITLE
Add pylibmc 1.5.2 for Python 2.7

### PR DESCRIPTION
**Pull request by cscetbon**

### CODE REVIEW

**Comment by Miserlou** [comment]
Great! But it looks like you have included some files specific to your local Vagrant in this commit, including what looks like a private key file. Maybe you want to clean those up in another commit?

**Comment by cscetbon** [comment]
Good catch @Miserlou ! `.vagrant` folder removed.

**Comment by Miserlou** [comment]
Nice! Sorry for not catching this before, but the format is also wrong (should be tgz not wheel), and you need an entry in the [manifest file](https://github.com/Miserlou/lambda-packages/blob/master/lambda_packages/__init__.py) for programmatic usage as well.

**Comment by cscetbon** [comment]
No worries @Miserlou. I've updated the code and now it generates it for both Python 2.7 and 3.6
Do you know any way to be able to build it with Docker for MacOs ? I still have the issue With CentOs and it's internal yum database being corrupted On MacOs as opposed to Linux. Switching from `overlays2` to `aufs` doesn't help

**Comment by Miserlou** [comment]
Brilliant!

**Comment by Miserlou** [comment]
I think you can use the LambCI docker image to build. 

With more resources, I'd really like to build out a proper system to build and sign lambda-packages rather than doing it in this ad-hoc way.

**Comment by cscetbon** [comment]
@Miserlou any reason why when I use `zappa package` I don't see any message saying it gets pylibmc from lambda package ?
```
$ pip freeze|grep -I pylibmc
pylibmc==1.5.2

$ zappa package
(python-dateutil 2.5.3 (/cscetbon/.virtualenvs/zappa/lib/python2.7/site-packages), Requirement.parse('python-dateutil==2.6.0'), set([u'zappa']))
Calling package for stage zqa..
Downloading and installing dependencies..
 - regex==2016.7.14: Warning! Using precompiled lambda package version 2016.8.27 instead!
 - psycopg2==2.6.2: Warning! Using precompiled lambda package version 2.6.1 instead!
 - msgpack-python==0.4.7: Using locally cached manylinux wheel
 - bcrypt==3.1.0: Using locally cached manylinux wheel
 - pillow==3.3.0: Using locally cached manylinux wheel
 - cffi==1.7.0: Using precompiled lambda package
Packaging project as zip..
```

**Comment by cscetbon** [comment]
@Miserlou did you see my previous message ? I haven't retried since I posted it

**Pull request merged**
