### PR TITLE
lxml added

### PR DESCRIPTION
**Pull request by cyril94440**
lxml compiled on Amazon Linux. Working well on Lambda.

### CODE REVIEW

**Comment by Miserlou** [comment]
Awesome!

We just need a few things before we can merge this:

The binary archive should be in the format lxml-{{version.number}}.targz
The lambda_packages.py manifest should be updated to include LXML.
A README or Vagrantfile should be included with steps to reproduce building this package.

Thanks for taking this on! This helps a lot of people.

**Comment by Miserlou** [comment]
Hey Cyril! This is just a reminder about getting this merged! Thanks!

**Comment by cyril94440** [comment]
Hey Miserlou,

sorry but I don't recall exactly what steps worked so it would have been time consuming to do it again. Anyway, this is working well on my lambda functions ;)

**Comment by Miserlou** [comment]
It's okay, I merged it anyway and left a warning in the README.md.

Eventually this whole thing will be automated, thank you for your contribution.

**Pull request merged**
