### PR TITLE
Python 3.6 Opencv 3.3

### PR DESCRIPTION
**Pull request by theochit**
Added support for python 3.6 opencv 3.3

### CODE REVIEW

**Comment by Miserlou** [comment]
You did it! Fantastic! 😄 : 

For this to be used by Zappa, you'll also need to modify the manifest in `__init__.py` - can you take care of that too?

**Comment by theochit** [comment]
Took long enough but I'm happy it's correct :) Yes I'll do it in 20 minutes

**Comment by theochit** [comment]
Is it supposed to be like the __init__.py in cryptography python 3.6? Including the author and system version?

**Comment by Miserlou** [comment]
Build failed :(

**Comment by Miserlou** [comment]
Hooray!

**Comment by theochit** [comment]
image
I'm not having a problem like this locally, is there anyway to check if I did this right..? All i'm doing is `pip install opencv-python` and `import cv2` on the sample django polls project (which I put on zappa first without error), so unfortunately I feel it's the package.

**Comment by theochit** [comment]
image
Think I found it. Do i need to open a new pull request?

**Pull request merged**
