### PR TITLE
Scikit Learn and Required Libraries

### PR DESCRIPTION
**Pull request by mcrowson**

### CODE REVIEW

**Comment by Miserlou** [comment]
This looks good, can you update the manifest file and the README, please?

Is there anyway to shrink that 27M tarball? That's a fat file.

**Comment by mcrowson** [comment]
Got it down to 25M without tests and precompiling. Running out the door so I'll double check next time to make sure i got everything.

**Comment by mcrowson** [comment]
Got it down to 24.1 MB and added some other packages

**Comment by Miserlou** [comment]
Theano and Keras are very welcome additions. Can you update the manifest file and README as well, please? I didn't get to push the 0.27.0 yesterday so this can still make it in.

**Comment by mcrowson** [comment]
Excuse the ignorance, but what would a manifest update look like?

**Comment by Miserlou** [comment]
Oh sorry, if you look in `lambda_packages/__init__.py`, you will see dictionary mapping the name of the install directory in site-packages to information about the version and a path to the directory of the tarball. This is how Zappa knows where to properly install the package.

**Comment by Miserlou** [comment]
It actually looks like it could do with a DRY refactor as well..

**Comment by mcrowson** [comment]
Do you intend to support multiple versions of a package?

**Comment by Miserlou** [comment]
I could envision a situation where that would be necessary. It hasn't come up yet but I could see it being a possibility if there are major changes between versions of a package.

**Comment by maebert** [comment]
Have you tried stripping unnecessary headers from binaries?

```
find “$VIRTUAL_ENV/lib*/python2.7/site-packages/” -name “*.so” | xargs strip
```

I [had some success with that](https://medium.com/@maebert/machine-learning-on-aws-lambda-5dc57127aee1#.tc2zmckzs) in the past to get the bundle size down.

**Comment by brendancol** [comment]
@Miserlou @maebert what's the next step for this PR?

**Comment by mcrowson** [comment]
I just need to take another look at it. I was trying various things to cut its size down and was seeing some strange things in lambda as a result. Just got distracted with other stuff, but I'll take another look this weekend.

**Comment by mcrowson** [comment]
@maebert when i try stripping the .so files i get these errors. 

BFD: lib64/python2.7/site-packages/scipy/fftpack/stbiZWA4: Not enough room for program headers, try linking with -N
strip:lib64/python2.7/site-packages/scipy/fftpack/stbiZWA4: Bad value

I get them for each of the errors for all of the .so files. Any ideas?

**Comment by mcrowson** [comment]
@brendancol We don't even need this PR anymore as scipy is supported through manylinux wheel. https://blog.zappa.io/posts/zappa-adds-support-for-manylinux-wheels.

Closing PR

**Pull request closed without merging**
