### PR TITLE
Added python-Levenshtein

### PR DESCRIPTION
**Pull request by brunoalano**

### CODE REVIEW

**Comment by Miserlou** [comment]
Sweet. Can I ask what you're using this stuff for?

**Comment by brunoalano** [comment]
They are useful for text processing tasks. The `datrie` package it's useful to build high performance suffixes tree, and this package for high performance word (or sentence) distance (it's not a real distance as meant in linear algebra).

But one question: should I add all those packages into `lambda-packages`, or it's possible to the user choose which packages he needs? Something like `pip install requests[security]`?

**Comment by brunoalano** [comment]
And I was thinking in keep available a public EC2 machine (since I receive credits as investment from them), to run an auto package builder for AWS Lambda

**Comment by Miserlou** [comment]
That's not a terrible idea given that this is starting to become quite a fat package. Please open a new ticket to discuss that though.

**Pull request merged**
