### PR TITLE
Fix package contents for Pillow.  Update pillow to 3.4.2

### PR DESCRIPTION
**Pull request by funkybob**
- DRY up the version number
- Only sudo for what we must
- Strip built libs
- Only include PIL and the libwebp libs.

### CODE REVIEW

**Comment by Miserlou** [comment]
NICE! Did you test this on Lambda?

**Comment by funkybob** [comment]
Yes, I'm now using this in my own project, which extracts EXIF data, and produces thumbnails... so basic smoke testing passes :)

**Comment by geeknam** [comment]
Thanks Curtis :)

**Comment by funkybob** [comment]
I've also managed to build Pillow-SIMD if you're interested.

**Pull request merged**
