### PR TITLE
Upgrade mysqlclient to 1.3.14

### PR DESCRIPTION
**Pull request by wolfg1969**
Django 2.2 will require mysqlclient >= 1.3.13

https://github.com/django/django/blob/2.2a1/django/db/backends/mysql/base.py#L36

Also removed the deprecated "--use-wheel" option of pip.

### CODE REVIEW

**Review by mbeacom — APPROVED** [review]

**Comment by tbaxx** [comment]
Please edit title to reflect correct mysqlclient version (1.3.14).

**Comment by wolfg1969** [comment]
@tbaxx Done.

**Comment by spinolacastro** [comment]
Hey guys, do you need some help to get this merged?

**Comment by celeduc** [comment]
Recent updates to Django and boto3 both require mysqlclient 1.3.13, so the currently available version bombs.  This is a real problem.

**Comment by rolexsanches** [comment]
Tested and working! Thanks!

**Comment by jonbesga** [comment]
Isn't this solved yet?

**Comment by khamaileon** [comment]
Up :/

**Comment by joinsito** [comment]
Any news on this?

**Comment by wolfg1969** [comment]
@joinsito No. Just waiting ...

**Comment by khamaileon** [comment]
@joinsito Or switch to AWS SAM ;)

**Comment by wolfg1969** [comment]
@khamaileon How to switch to AWS SAM? Is it a smooth way?

**Comment by guilhermej** [comment]
Hey, this is several months late, can you @Miserlou just accept it?
Is this project dead?

**Comment by brett-matthews** [comment]
Would <3 this to be merged and applied to zappa requirements

**Comment by losnuyh** [comment]
image

I want to upgrade 2.2 (LST)

**Comment by wolfg1969** [comment]
Zappa 0.5.1 adds layers support.

**Pull request closed without merging**
